// <auto-generated />
using Account.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Account.Persistence.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Account.Persistence.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ioanvalentincernovschi@gmail.com",
                            FirstName = "Ioan",
                            LastName = "Cernovschi",
                            Password = "tavi",
                            PhoneNumber = "0700000000"
                        },
                        new
                        {
                            Id = 2,
                            Email = "tavi22015@gmail.com",
                            FirstName = "Octavian",
                            LastName = "Ungureanu",
                            Password = "john",
                            PhoneNumber = "0700000001"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mihneav@gmail.com",
                            FirstName = "Mihnea",
                            LastName = "Voronca",
                            Password = "kati",
                            PhoneNumber = "0700000002"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
